### ISSUE TITLE
dbeaver 不支持

### ISSUE THREAD

**Issue by hope250** [SeptemberHX/Chameleon-patched#2]
dbeaver 不支持

**Comment by SeptemberHX** [comment]
修改文件 ~/.gtkrc-2.0 ，添加 gtk-modules=appmenu-gtk-module
修改文件 ～/.config/gtk-3.0/settings.ini ，[Settings] 条目下 添加 gtk-modules=appmenu-gtk-module

![image](https://user-images.githubusercontent.com/18042424/129661519-d06aa5ae-2f06-4bee-bf3b-843162f22ad0.png)

**Comment by hope250** [comment]
> 修改文件 ~/.gtkrc-2.0 ，添加 gtk-modules=appmenu-gtk-module
> 修改文件 ～/.config/gtk-3.0/settings.ini ，[Settings] 条目下 添加 gtk-modules=appmenu-gtk-module
> 
> ![image](https://user-images.githubusercontent.com/18042424/129661519-d06aa5ae-2f06-4bee-bf3b-843162f22ad0.png)

已修改配置，dbeaver 适配，

但是又发现 Filezilla 不适配，请问如何处理。

**Comment by SeptemberHX** [comment]
![image](https://user-images.githubusercontent.com/18042424/129662196-4f983153-9025-46d2-8900-dc98a45464fb.png)

我这边正常。你的 filezilla 是从哪里下载的？我是商店里直接安装的

**Comment by hope250** [comment]
> ![image](https://user-images.githubusercontent.com/18042424/129662196-4f983153-9025-46d2-8900-dc98a45464fb.png)
> 
> 我这边正常。你的 filezilla 是从哪里下载的？我是商店里直接安装的

我的版本 3.54.1，是从 Filezilla 官网下载的二进制版

**Comment by SeptemberHX** [comment]
![image](https://user-images.githubusercontent.com/18042424/129662385-db5a876f-e82a-4d52-b957-291d1f608a22.png)

我下载的二进制最新版 3.55.1 也是正常的

**Comment by hope250** [comment]
> ![image](https://user-images.githubusercontent.com/18042424/129662385-db5a876f-e82a-4d52-b957-291d1f608a22.png)
> 
> 我下载的二进制最新版 3.55.1 也是正常的

难道还有其他配置需要调整吗？
我也重新下载了3.55.1，而且我把filezilla配置文件也移除，让他处于完全初始的状态，标题栏还是不能适配。

**Comment by hope250** [comment]
找到问题症结了，我从命令行启动 Filezilla，发现了一条报错信息。
`Gtk-Message: 12:15:44.333: Failed to load module "appmenu-gtk-modulegtk-modules"
/home/username/.gtkrc-2.0:2: error: unexpected character '=', expected keyword - e.g. `style'`

我再次打开 ~/.gtkrc-2.0 ，确实发现了内容格式错误，该文件自动被追加了`gtk-modules=appmenu-gtk-module`，但是没有换行。

不知道是不是 dde-globalmenu-service 有自动调整配置的代码，但是没有添加换行符。

又或者是我自己不小心复制粘贴了多次？

目前，保持配置的格式正确，Filezilla已经正常适配。

**Comment by SeptemberHX** [comment]
啊，好像是有这么一回事，dde-globalmenu-service 会自动添加配置，后面改一改。
